# Generated by Django 5.0.6 on 2024-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
