# Generated by Django 5.0.6 on 2024-06-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cars_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
